const {chromium} = require('playwright');
const assert = require('node:assert/strict');
(async () => {
 const browser = await chromium.launch({executablePath:process.env.MOBILE_BROWSER_EXECUTABLE, args:['--no-sandbox']});
 const context = await browser.newContext({viewport:{width:390,height:844}});
 const page = await context.newPage();
 const errors=[]; page.on('pageerror', e=>errors.push(e.message));
 let roles=['team_representative'], empty=false;
 const calls=[];
 const stats={points:12,receptions:3,tackles:4,interceptions:1,sacks:2,passes_completed:2,passes_attempted:4,completion_percentage:50};
 const teams=[1,2].map(id=>({id,name:`Equipo ${id}`,branch:'mixto',category:'u8',logo_url:null,roster_count:1,head_coach:'Entrenador',coach:null,manager:null,standing:{wins:1,losses:0,points_for:12,points_against:0,point_difference:12,position:1,division_team_count:2},statistics:stats,players:[{player_id:id,player_name:`Jugador ${id}`,player_aka:null,jersey_number:id,...stats}]}));
 const games=[{id:1,home_team:{id:1,name:'Equipo 1'},away_team:{id:99,name:'Rival A'},status:'scheduled',home_score:null,away_score:null,week:1,start_time:'10:00:00',field_number:1},{id:2,home_team:{id:2,name:'Equipo 2'},away_team:{id:99,name:'Rival B'},status:'completed',home_score:12,away_score:0,week:1,start_time:'11:00:00',field_number:2},{id:3,home_team:{id:98,name:'Equipo ajeno'},away_team:{id:99,name:'Rival ajeno'},status:'scheduled',home_score:null,away_score:null,week:1,start_time:'12:00:00',field_number:2}];
 await context.addInitScript(()=>localStorage.setItem('flagtastic_session','test-token'));
 await page.route('https://flagtastic.online/api/**', async route=>{
  const path=new URL(route.request().url()).pathname;calls.push(path);
  let data;
  if(path==='/api/auth/me')data={id:1,name:'Representante Prueba',display_name:'Representante Prueba',roles};
  else if(path==='/api/me/representative-dashboard')data={teams:empty?[]:teams};
  else if(path==='/api/games')data=games;
  else if(path==='/api/standings')data=teams.map(t=>({team_id:t.id,team_name:t.name,...t.standing}));
  else if(path==='/api/statistics/leaderboards')data={};
  else if(path==='/api/referees/me')data={id:1,name:'Representante Prueba',display_name:'Representante Prueba',profile_photo_url:null};
  else if(path==='/api/games/mine/referee')data=[];
  else if(path==='/api/me/dashboard')data={player:{id:1,name:'Jugador Prueba',aka:null,profile_photo_url:null},teams:[],statistics:{weeks:0,...stats}};
  else throw new Error(`Unexpected endpoint ${path}`);
  await route.fulfill({json:data});
 });
 await page.goto(process.env.MOBILE_TEST_URL || 'http://localhost:8081');
 await page.getByText('REPRESENTANTE',{exact:true}).waitFor();
 await page.getByText('Ver plantel y estadísticas →').first().click();
 await page.getByText('Plantel activo',{exact:true}).waitFor();
 await page.getByText('Jugador 1',{exact:true}).waitFor();
 await page.getByText('Equipo 2 · U8',{exact:true}).last().click();
 await page.getByText('Jugador 2',{exact:true}).waitFor();
 await page.getByRole('tab',{name:'Partidos'}).click();
 await page.getByText('Ver todos mis equipos →',{exact:true}).click();
 await page.getByText('Equipo 1 vs Rival A',{exact:true}).waitFor();
 assert.equal(await page.getByText('Equipo ajeno vs Rival ajeno',{exact:true}).count(),0);
 await page.getByText('Resultados',{exact:true}).click();
 await page.getByText('Equipo 2 vs Rival B',{exact:true}).waitFor();
 assert(!calls.includes('/api/me/dashboard'), 'representative-only account fetched player dashboard');
 if (process.env.MOBILE_SCREENSHOT_PATH) await page.screenshot({path:process.env.MOBILE_SCREENSHOT_PATH});
 // Empty assignment and all-role switching, including return to native representative tabs.
 empty=true; await page.reload();
 await page.getByText('Sin equipos asignados',{exact:true}).waitFor();
 empty=false; roles=['team_representative','player','referee'];await page.reload();
 await page.getByText('Mi arbitraje',{exact:true}).waitFor();
 await page.getByRole('tab',{name:'Mi perfil'}).click();
 await page.getByText('Cambiar a representante',{exact:true}).click();
 await page.getByText('REPRESENTANTE',{exact:true}).waitFor();
 await page.getByRole('tab',{name:'Mi perfil'}).click();
 await page.getByText('Cambiar a jugador',{exact:true}).click();
 await page.getByText('Aún no tienes equipo',{exact:true}).waitFor();
 assert.equal(errors.length,0,errors.join('\n'));
 console.log('PASS: representative-only restoration, roster/team switching, scoped agenda/results, empty teams, and three-role switching.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
